/**
 * Manual ticker → sub-industry mapping for heatmap grouping.
 * Yahoo batch quote doesn't return industry, so we map it statically.
 */
export const SUB_INDUSTRY_MAP: Record<string, string> = {
  // === XLU: Utilities ===
  CEG: "Electric Utilities",  SO: "Electric Utilities",  DUK: "Electric Utilities",
  NEE: "Electric Utilities",  SRE: "Electric Utilities",  AEP: "Electric Utilities",
  D: "Electric Utilities",  EXC: "Electric Utilities",  XEL: "Electric Utilities",
  WEC: "Electric Utilities",  ED: "Electric Utilities",  PEG: "Electric Utilities",
  ES: "Electric Utilities",  AEE: "Electric Utilities",  CMS: "Electric Utilities",
  PPL: "Electric Utilities",  ETR: "Electric Utilities",  FE: "Electric Utilities",
  NRG: "Power Generation",  EIX: "Electric Utilities",  DTE: "Electric Utilities",
  VST: "Power Generation",  FTS: "Electric Utilities",  CNP: "Electric Utilities",
  NI: "Electric Utilities",  PCG: "Electric Utilities",  EMA: "Electric Utilities",
  PNW: "Electric Utilities",  AES: "Power Generation",  OGE: "Electric Utilities",
  AWK: "Water Supply",  EVRG: "Electric Utilities",  LNT: "Electric Utilities",
  ATO: "Natural Gas Distribution",  RSG: "Environmental Services",
  WMB: "Oil/Gas Transmission",  EPD: "Oil/Gas Transmission",  TRGP: "Oil/Gas Transmission",
  KMI: "Oil/Gas Transmission",  OKE: "Oil/Gas Transmission",  ET: "Oil/Gas Transmission",
  AM: "Oil/Gas Transmission",  SREA: "Oil & Gas Production",  DTM: "Oil/Gas Transmission",
  KNTK: "Oil/Gas Transmission",  AROC: "Oil/Gas Transmission",  WES: "Oil/Gas Transmission",
  CWEN: "Power Generation",  BKH: "Electric Utilities",  ORA: "Power Generation",
  IDA: "Electric Utilities",  POR: "Electric Utilities",  VG: "Oil & Gas Production",
  NFG: "Natural Gas Distribution",  WTRG: "Water Supply",  CIEN: "Telecommunications Equipment",
  SJW: "Water Supply",

  // === XLK: Technology ===
  AAPL: "Consumer Electronics",  MSFT: "Software—Infrastructure",  NVDA: "Semiconductors",
  AVGO: "Semiconductors",  CRM: "Software—Application",  AMD: "Semiconductors",
  ADBE: "Software—Application",  CSCO: "Communication Equipment",  ACN: "IT Services",
  ORCL: "Software—Infrastructure",  INTC: "Semiconductors",  QCOM: "Semiconductors",
  IBM: "IT Services",  TXN: "Semiconductors",  AMAT: "Semiconductor Equipment",
  LRCX: "Semiconductor Equipment",  MU: "Semiconductors",  KLAC: "Semiconductor Equipment",
  ADI: "Semiconductors",  SNPS: "Software—Application",  CDNS: "Software—Application",
  MRVL: "Semiconductors",  FTNT: "Software—Infrastructure",  PANW: "Software—Infrastructure",
  MSI: "Communication Equipment",  APH: "Electronic Components",  NXPI: "Semiconductors",
  ON: "Semiconductors",  MPWR: "Semiconductors",  MCHP: "Semiconductors",
  TEL: "Electronic Components",  KEYS: "Scientific Instruments",  CDW: "IT Services",
  GLW: "Electronic Components",  TYL: "Software—Application",  ZBRA: "Electronic Components",
  TRMB: "Scientific Instruments",  EPAM: "IT Services",  ENPH: "Solar Technology",
  SMCI: "Computer Hardware",  FSLR: "Solar Technology",  ANET: "Communication Equipment",
  NOW: "Software—Application",  PLTR: "Software—Application",  CRWD: "Software—Infrastructure",
  GDDY: "Software—Application",  GEN: "Software—Infrastructure",  JNPR: "Communication Equipment",
  HPE: "Computer Hardware",  HPQ: "Computer Hardware",  WDC: "Data Storage",  STX: "Data Storage",

  // === XLE: Energy ===
  XOM: "Oil & Gas Integrated",  CVX: "Oil & Gas Integrated",  COP: "Oil & Gas E&P",
  EOG: "Oil & Gas E&P",  SLB: "Oil & Gas Equipment",  MPC: "Oil & Gas Refining",
  PSX: "Oil & Gas Refining",  VLO: "Oil & Gas Refining",  OXY: "Oil & Gas E&P",
  HES: "Oil & Gas E&P",  DVN: "Oil & Gas E&P",  BKR: "Oil & Gas Equipment",
  FANG: "Oil & Gas E&P",  HAL: "Oil & Gas Equipment",
  MRO: "Oil & Gas E&P",  APA: "Oil & Gas E&P",  EQT: "Natural Gas",
  CHRD: "Oil & Gas E&P",  PR: "Oil & Gas E&P",  SM: "Oil & Gas E&P",
  RRC: "Natural Gas",  AR: "Natural Gas",  SWN: "Natural Gas",
  MGY: "Oil & Gas E&P",  MTDR: "Oil & Gas E&P",
  DINO: "Oil & Gas Refining",  PBF: "Oil & Gas Refining",  DK: "Oil & Gas Refining",
  CTRA: "Oil & Gas E&P",
  NOV: "Oil & Gas Equipment",  FTI: "Oil & Gas Equipment",  WFRD: "Oil & Gas Equipment",
  RIG: "Oil & Gas Drilling",  HP: "Oil & Gas Drilling",  PTEN: "Oil & Gas Drilling",
  LBRT: "Oil & Gas Equipment",

  // === XLF: Financials ===
  "BRK-B": "Diversified Financial",  JPM: "Banks—Diversified",  V: "Credit Services",
  MA: "Credit Services",  BAC: "Banks—Diversified",  WFC: "Banks—Diversified",
  GS: "Capital Markets",  MS: "Capital Markets",  SPGI: "Financial Data",
  AXP: "Credit Services",  C: "Banks—Diversified",  BLK: "Asset Management",
  SCHW: "Capital Markets",  CB: "Insurance—P&C",  MMC: "Insurance Brokers",
  PGR: "Insurance—P&C",  CME: "Financial Exchanges",  ICE: "Financial Exchanges",
  AON: "Insurance Brokers",  MCO: "Financial Data",
  MET: "Insurance—Life",  AIG: "Insurance—Diversified",  PRU: "Insurance—Life",
  TRV: "Insurance—P&C",  AFL: "Insurance—Life",  ALL: "Insurance—P&C",
  HIG: "Insurance—P&C",  WRB: "Insurance—P&C",  GL: "Insurance—Life",
  FITB: "Banks—Regional",  MTB: "Banks—Regional",  HBAN: "Banks—Regional",
  KEY: "Banks—Regional",  CFG: "Banks—Regional",  RF: "Banks—Regional",
  ZION: "Banks—Regional",  CMA: "Banks—Regional",
  TROW: "Asset Management",  NTRS: "Asset Management",  STT: "Asset Management",
  BEN: "Asset Management",  IVZ: "Asset Management",
  COIN: "Financial Exchanges",  HOOD: "Capital Markets",

  // === XLV: Health Care ===
  UNH: "Health Care Plans",  LLY: "Drug Manufacturers",  JNJ: "Drug Manufacturers",
  ABBV: "Drug Manufacturers",  MRK: "Drug Manufacturers",  TMO: "Diagnostics & Research",
  ABT: "Medical Devices",  DHR: "Diagnostics & Research",  PFE: "Drug Manufacturers",
  AMGN: "Biotechnology",  ISRG: "Medical Instruments",  SYK: "Medical Devices",
  GILD: "Biotechnology",  VRTX: "Biotechnology",  MDT: "Medical Devices",
  ELV: "Health Care Plans",  REGN: "Biotechnology",  BDX: "Medical Instruments",
  BSX: "Medical Devices",  ZTS: "Drug Manufacturers",
  DXCM: "Medical Devices",  IQV: "Diagnostics & Research",  IDXX: "Diagnostics & Research",
  A: "Diagnostics & Research",  WAT: "Diagnostics & Research",
  BAX: "Medical Instruments",  EW: "Medical Devices",  HOLX: "Medical Instruments",
  ALGN: "Medical Devices",  RMD: "Medical Devices",
  HCA: "Health Care Providers",  CNC: "Health Care Plans",  MOH: "Health Care Plans",
  CI: "Health Care Plans",  CVS: "Health Care Providers",
  BIIB: "Biotechnology",  MRNA: "Biotechnology",  NBIX: "Biotechnology",
  INCY: "Biotechnology",  ALNY: "Biotechnology",

  // === XLY: Consumer Discretionary ===
  AMZN: "Internet Retail",  TSLA: "Auto Manufacturers",  HD: "Home Improvement",
  MCD: "Restaurants",  NKE: "Footwear & Accessories",  LOW: "Home Improvement",
  BKNG: "Travel Services",  SBUX: "Restaurants",  TJX: "Apparel Retail",
  CMG: "Restaurants",  ORLY: "Auto Parts",  MAR: "Lodging",  HLT: "Lodging",
  AZO: "Auto Parts",  ROST: "Apparel Retail",  DHI: "Residential Construction",
  LEN: "Residential Construction",  YUM: "Restaurants",  EBAY: "Internet Retail",
  LULU: "Apparel Retail",
  GM: "Auto Manufacturers",  F: "Auto Manufacturers",  APTV: "Auto Parts",
  GRMN: "Consumer Electronics",  BBY: "Specialty Retail",  DPZ: "Restaurants",
  WYNN: "Resorts & Casinos",  LVS: "Resorts & Casinos",  MGM: "Resorts & Casinos",
  CZR: "Resorts & Casinos",  RCL: "Travel Services",  CCL: "Travel Services",
  NCLH: "Travel Services",  HAS: "Leisure",  POOL: "Specialty Retail",
  WSM: "Home Furnishings",  DECK: "Footwear & Accessories",  BURL: "Apparel Retail",
  KMX: "Auto Parts",  GPC: "Auto Parts",  DRI: "Restaurants",
  TXRH: "Restaurants",  EAT: "Restaurants",  WING: "Restaurants",

  // === XLC: Communication Services ===
  META: "Internet Content",  GOOGL: "Internet Content",  GOOG: "Internet Content",
  NFLX: "Entertainment",  DIS: "Entertainment",  CMCSA: "Telecom Services",
  TMUS: "Telecom Services",  VZ: "Telecom Services",  T: "Telecom Services",
  CHTR: "Telecom Services",  EA: "Electronic Gaming",  TTWO: "Electronic Gaming",
  OMC: "Advertising",  IPG: "Advertising",  WBD: "Entertainment",
  PARA: "Entertainment",  FOXA: "Broadcasting",  FOX: "Broadcasting",
  LYV: "Entertainment",  MTCH: "Internet Content",
  RBLX: "Electronic Gaming",  ZM: "Software—Application",  SPOT: "Internet Content",
  PINS: "Internet Content",  SNAP: "Internet Content",  ROKU: "Entertainment",
  TTD: "Advertising",  NWSA: "Publishing",  NWS: "Publishing",

  // === XLI: Industrials ===
  CAT: "Farm & Heavy Equipment",  RTX: "Aerospace & Defense",  UNP: "Railroads",
  HON: "Diversified Industrials",  DE: "Farm & Heavy Equipment",  BA: "Aerospace & Defense",
  LMT: "Aerospace & Defense",  GE: "Diversified Industrials",  UPS: "Integrated Freight",
  ADP: "Staffing & Employment",  WM: "Waste Management",  ETN: "Electrical Equipment",
  MMM: "Diversified Industrials",  NOC: "Aerospace & Defense",  GD: "Aerospace & Defense",
  CSX: "Railroads",  ITW: "Specialty Industrial",  EMR: "Electrical Equipment",
  NSC: "Railroads",  TDG: "Aerospace & Defense",
  FDX: "Integrated Freight",  LHX: "Aerospace & Defense",  CARR: "Building Products",
  OTIS: "Specialty Industrial",  PH: "Specialty Industrial",  ROK: "Electrical Equipment",
  SWK: "Tools & Accessories",  CMI: "Specialty Industrial",  FAST: "Industrial Distribution",
  PCAR: "Truck Manufacturing",  JCI: "Building Products",  GWW: "Industrial Distribution",
  IR: "Specialty Industrial",  DOV: "Specialty Industrial",  AME: "Electrical Equipment",
  DAL: "Airlines",  UAL: "Airlines",  LUV: "Airlines",  AAL: "Airlines",

  // === XLP: Consumer Staples ===
  PG: "Household Products",  COST: "Discount Stores",  KO: "Beverages—Non-Alcoholic",
  PEP: "Beverages—Non-Alcoholic",  WMT: "Discount Stores",  PM: "Tobacco",
  MDLZ: "Packaged Foods",  MO: "Tobacco",  CL: "Household Products",
  STZ: "Beverages—Alcoholic",  KMB: "Household Products",  GIS: "Packaged Foods",
  SYY: "Food Distribution",  KHC: "Packaged Foods",  HSY: "Confectioners",
  MKC: "Packaged Foods",  TSN: "Farm Products",  K: "Packaged Foods",
  HRL: "Packaged Foods",  SJM: "Packaged Foods",
  ADM: "Farm Products",  CAG: "Packaged Foods",  CPB: "Packaged Foods",
  MNST: "Beverages—Non-Alcoholic",  KDP: "Beverages—Non-Alcoholic",
  EL: "Personal Products",  CHD: "Household Products",  CLX: "Household Products",
  TAP: "Beverages—Alcoholic",  KR: "Grocery Stores",  CASY: "Grocery Stores",

  // === XLB: Materials ===
  LIN: "Specialty Chemicals",  SHW: "Specialty Chemicals",  APD: "Specialty Chemicals",
  ECL: "Specialty Chemicals",  NUE: "Steel",  FCX: "Copper",
  DD: "Specialty Chemicals",  DOW: "Chemicals",  VMC: "Building Materials",
  MLM: "Building Materials",  NEM: "Gold",  PPG: "Specialty Chemicals",
  CTVA: "Agricultural Inputs",  ALB: "Specialty Chemicals",  CE: "Chemicals",
  EMN: "Specialty Chemicals",  IP: "Packaging",  PKG: "Packaging",
  FMC: "Agricultural Inputs",  CF: "Agricultural Inputs",
  RPM: "Specialty Chemicals",  AVY: "Packaging",  SEE: "Packaging",
  SON: "Packaging",  WRK: "Packaging",
  GOLD: "Gold",  AEM: "Gold",  KGC: "Gold",  WPM: "Gold",  FNV: "Gold",
  STLD: "Steel",  RS: "Steel",  CLF: "Steel",  RGLD: "Gold",

  // === XLRE: Real Estate ===
  PLD: "Industrial REITs",  AMT: "Infrastructure REITs",  CCI: "Infrastructure REITs",
  EQIX: "Data Center REITs",  PSA: "Self-Storage REITs",  SPG: "Retail REITs",
  O: "Retail REITs",  DLR: "Data Center REITs",  WELL: "Health Care REITs",
  VICI: "Specialty REITs",  AVB: "Residential REITs",  EQR: "Residential REITs",
  ARE: "Office REITs",  MAA: "Residential REITs",  ESS: "Residential REITs",
  UDR: "Residential REITs",  CPT: "Residential REITs",  VTR: "Health Care REITs",
  HST: "Hotel REITs",  KIM: "Retail REITs",
  REG: "Retail REITs",  FRT: "Retail REITs",  BXP: "Office REITs",
  SLG: "Office REITs",  VNO: "Office REITs",  CBRE: "Real Estate Services",
  JLL: "Real Estate Services",  IRM: "Specialty REITs",  CUBE: "Self-Storage REITs",
  EXR: "Self-Storage REITs",  INVH: "Residential REITs",  SUI: "Residential REITs",
  ELS: "Residential REITs",  MPW: "Health Care REITs",  OHI: "Health Care REITs",
  PEAK: "Health Care REITs",
};
